### ISSUE TITLE
Parsing error loading Advancement Modifier: bayou_blues:find_natural_slabfish

### ISSUE THREAD

**Issue by kalinzange** [teamauroramods/BayouBlues#27]
I'm using [Better Advancements Mod](https://www.curseforge.com/minecraft/mc-mods/better-advancements) and whenever I start the server I get the following error:

Minecraft Version: 1.16.5
Forge Version: 36.1.0

```
[15:37:29] [Worker-Main-14/ERROR] [co.mi.ab.co.AbnormalsCore/]: Parsing error loading Advancement Modifier: bayou_blues:find_natural_slabfish
com.google.gson.JsonSyntaxException: Invalid criterion trigger: environmental:slabfish
        at net.minecraft.advancements.Criterion.func_232633_a_(SourceFile:34) ~[?:?] {re:classloading}
        at net.minecraft.advancements.Criterion.func_232634_b_(SourceFile:47) ~[?:?] {re:classloading}
        at com.minecraftabnormals.abnormals_core.common.advancement.modification.modifiers.CriteriaModifier.lambda$new$0(CriteriaModifier.java:31) ~[abnormals_core:3.1.1] {re:classloading}
        at com.minecraftabnormals.abnormals_core.common.advancement.modification.AdvancementModifier.deserialize(AdvancementModifier.java:37) ~[abnormals_core:3.1.1] {re:classloading}
        at com.minecraftabnormals.abnormals_core.common.advancement.modification.AdvancementModificationManager.lambda$deserializeModifiers$1(AdvancementModificationManager.java:106) ~[abnormals_core:3.1.1] {re:classloading}
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_281] {}
        at com.minecraftabnormals.abnormals_core.common.advancement.modification.AdvancementModificationManager.deserializeModifiers(AdvancementModificationManager.java:94) ~[abnormals_core:3.1.1] {re:classloading}
        at com.minecraftabnormals.abnormals_core.common.advancement.modification.AdvancementModificationManager.apply(AdvancementModificationManager.java:120) ~[abnormals_core:3.1.1] {re:classloading}
        at com.minecraftabnormals.abnormals_core.common.advancement.modification.AdvancementModificationManager.func_212853_a_(AdvancementModificationManager.java:36) ~[abnormals_core:3.1.1] {re:classloading}
        at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading,re:mixin}
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_281] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_281] {}

**Comment by Klouver0X** [comment]
i am having same issue I am not sure this causing the whole Safe Mode or Menu Screen buttons to pop up and not let me load worlds
